#Problem 1

det(h) =
$\frac{1}{\sqrt{2}}$ $\begin{bmatrix}
1 & 1 \\
1 &-1
\end{bmatrix}$


In [9]:
import numpy as np


matrix = 1/np.sqrt(2) * np.array([[1, 1],
                            [1,-1]])

determinant = np.linalg.det(matrix)
print(matrix)
print(determinant)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
-0.9999999999999999


#Problem 2
det(Y) =
 $\begin{bmatrix}
0 & -i \\
i &0
\end{bmatrix}$


In [11]:
#Problem 2
import numpy as np

# Define the imaginary unit
i = 1j

# Create the matrix with complex numbers
matrix = np.array([[0, -i],
                  [i, 0]])

# Calculate the determinant
determinant = np.linalg.det(matrix)

# Print the matrix and determinant
print(matrix)
print(determinant)

[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
(-1+0j)


#Problem 3
H = $\frac{1}{\sqrt{2}} \begin{bmatrix}
1 & 1 \\
1 & -1
\end{bmatrix} * Y =\begin{bmatrix}
0 & -i \\
i & 0
\end{bmatrix}$



In [18]:
#Problem 3
import numpy as np

H = 1/np.sqrt(2) * np.array([[1, 1],
                            [1,-1]])
Y = np.array([[0, -i],
                  [i, 0]])
O = np.array ([[1,0],[1,1]])

ans = np.dot (H,Y)
print (ans)

[[0.+0.70710678j 0.-0.70710678j]
 [0.-0.70710678j 0.-0.70710678j]]


In [14]:
#Problem 4
Y @ H

array([[0.-0.70710678j, 0.+0.70710678j],
       [0.+0.70710678j, 0.+0.70710678j]])

In [16]:
#Problem 5
H @ H

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

In [19]:
#Problem 6
Y @ H @ O

array([[0.+0.j        , 0.+0.70710678j],
       [0.+1.41421356j, 0.+0.70710678j]])

In [21]:
#Problem 7
H @ Y @ H @ O

array([[0.+1.00000000e+00j, 0.+1.00000000e+00j],
       [0.-1.00000000e+00j, 0.+2.23711432e-17j]])